### ISSUE TITLE
Move building code out of src

### ISSUE THREAD

**Issue by jeluard** [ChainSafe/blst-ts#117]
End-user code and code used to generate bindings are currently mixed in `src`. Similarly, required `dependencies` are added to the same module.

Find a way to separate both so that only the end user code is bundled, and no extra dependencies are leaked downstream.

**Comment by matthewkeil** [comment]
A best effort was made to support this.  There are a couple more items that need to be handled in upcoming PR.
- Remove `ts-node` from deps (used for running `scripts/install.ts`)

**Comment by philknows** [comment]
No longer relevant after napi-rs refactor. Closing.
