### ISSUE TITLE
Roll your own http client

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/blst-ts#15]
To remove the dependency `node-fetch` consider writing an HTTP client to download a Github release asset to disk. Note it must
- Follow N redirects
- Handle networks errors
- Handle fs errors
- Have a timeout
- Retry?

https://github.com/ChainSafe/lodestar/pull/1783#discussion_r528211229

Proposed initial code by @mpetrunic 
```ts
const https = require('https');
const fs = require('fs');

const file = fs.createWriteStream("./binding.node");
const request = https.get("<release url>", (response) => {
  if(response.statusCode == 302) {
     https.get(response.headers.location, (res) => {
        res.pipe(file);
     })
  } else {
     response.pipe(file);
  }
});
```

**Comment by matthewkeil** [comment]
Closing.  `node-fetch` removed by #131
