### ISSUE TITLE
Wasm version

### ISSUE THREAD

**Issue by paulmillr** [ChainSafe/blst-ts#18]
Would be great to be able to run the lib in browser

**Comment by dapplion** [comment]
I know!

**Comment by nazarhussain** [comment]
@paulmillr You can try using this for the browsers https://github.com/ChainSafe/bls

**Comment by paulmillr** [comment]
@nazarhussain blst is reference bls implementation that was thoroughly audited

You're suggesting to use herumi/bls, which does not have these properties & much slower

**Comment by nazarhussain** [comment]
I suggested for browser use. And any browser compatible implementation will be slower than BLS which is most of assembly language implementation.

**Comment by paulmillr** [comment]
I have developed [pure-javascript bls library](https://github.com/paulmillr/noble-bls12-381) one year ago. The goal here is not to use "something" in browser, it is to use blst in browser.

**Comment by dapplion** [comment]
> I suggested for browser use. And any browser compatible implementation will be slower than BLS which is most of assembly language implementation.

BLST should be compilable to WASM, but we have no bandwidth to make that happen now

**Comment by bryanchriswhite** [comment]
I've been working on this for a bit and thought I would share: https://github.com/fetchai/blst-ts/pull/1. It's not my top priority but I'm anxious to done and I've been grinding on it in-between other tasks. My first goal was to get the [blst-sample-case]() passing in the browser. So far I've been able to get all of the [bindings tests]() passing. I seem to have everything working except for P1/P2 `hash_to` and `encode_to` (therefore, [blst-sample-case.test.ts]() is still failing).

**Comment by matthewkeil** [comment]
Browser support is provided via https://github.com/supranational/blst/tree/master/bindings/emscripten and also via https://github.com/ChainSafe/bls . This repos now hosts napi async bindings for multi-threaded verification and is node specific. There is some discussion about building multi-threaded wasm or emscripten bindings but that is still a future "wish list" thing.  Closing this issue

**Comment by z496090280** [comment]
> I have developed [pure-javascript bls library](https://github.com/paulmillr/noble-bls12-381) one year ago. The goal here is not to use "something" in browser, it is to use blst in browser.

whypure-javascript bls library sign verify result false，This library results in true

**Comment by z496090280** [comment]
> I have developed [pure-javascript bls library](https://github.com/paulmillr/noble-bls12-381) one year ago. The goal here is not to use "something" in browser, it is to use blst in browser.

why pure-javascript bls library sign verify result false，This library results in true

**Comment by z496090280** [comment]
![image](https://github.com/user-attachments/assets/f5b8b395-4fbf-47ef-b3ca-2c2818b7fe8a)
