### ISSUE TITLE
Incorrect result for zero lengths arrays in aggregateVerify

### ISSUE THREAD

**Issue by dnkolegov** [ChainSafe/blst-ts#43]
**Describe the bug**

[aggregateVerify](https://github.com/ChainSafe/blst-ts/blob/master/src/lib.ts) doesn't check the size of public keys/messages arrays. A zero-length array is possible.

The spec requires the [following](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-04#section-3.1.1): Precondition: n >= 1, otherwise return INVALID. 

So, the function must throw `ErrorBLST(BLST_ERROR.BLST_VERIFY_FAIL)` to be consistent.
But if len(msgs) and len(pks) are equal to 0 then for loop on 238-243 lines will be skipped and `ctx.finalverify()` will be executed. The last one returns a bool value. That is inconsistent with lines 232-234.

**Expected behavior**
To throw an ErrorBLST(BLST_ERROR.BLST_VERIFY_FAIL) to be consistent with the following:
```
if (msgs.length !== n_elems) {    
    throw new ErrorBLST(BLST_ERROR.BLST_VERIFY_FAIL);
}
```

**Comment by dapplion** [comment]
Thanks for reporting!
