### ISSUE TITLE
v0.2.4 release failed

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/blst-ts#58]
**Describe the bug**

See https://github.com/ChainSafe/blst-ts/runs/5293896672?check_suite_focus=true

**Expected behavior**

No error

**Comment by dapplion** [comment]
I think originally it didn't build bindings for NodeJS < 12 for Windows. Could you double check?

**Comment by wemeetagain** [comment]
Can we drop support for < 12 ?

**Comment by dapplion** [comment]
> Can we drop support for < 12 ?

If bindings work no, it's free for us to support NodeJS v12. There are still many people running v12

**Comment by wemeetagain** [comment]
v12 reached end of life https://nodejs.org/en/about/releases/

**Comment by dapplion** [comment]
Once builds for Node < 12 fail we can drop them. However in the meantime it's free to support them
