### ISSUE TITLE
Support for Apple Silicon (M1, M2 chips)

### ISSUE THREAD

**Issue by nzhl** [ChainSafe/blst-ts#85]
Any plan or ETA for Apple Silicon ?

**Comment by dapplion** [comment]
Awaiting a runner to compile on that architecture, see

https://github.com/ChainSafe/blst-ts/blob/6ff826db02a1c5363d30e67785742b85c9172dea/README.md?plain=1#L19

**Comment by nzhl** [comment]
Yeah, i think it's currently working fine for Apple Silicon, at least working on my m1 mba. If you encouter any error during installation, install python2.x on your machine (which is not installed by default) and try again
